name: 'build-test'
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
      - ready_for_review
jobs:
  build:
    runs-on:
      - self-hosted
      - Linux
      - Basic
    container:
      image: node:12
      # https://github.com/actions/runner/issues/691
      options: --user 1000
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run all
  test: # make sure the action works on a clean machine without building
    container:
      image: node:12
      # https://github.com/actions/runner/issues/691
      options: --user 1000
    runs-on:
      - self-hosted
      - Linux
      - Basic
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id: commitMessage
      - run: echo "${{ steps.commitMessage.outputs.commitText }}"
